const API="https://ludo-inspire.onrender.com";let token=localStorage.getItem("ludo_token"),currentRoom=null;const $=id=>document.getElementById(id);
async function api(path,opt={}){opt.headers={...(opt.headers||{}),"Content-Type":"application/json"};if(token)opt.headers.Authorization="Bearer "+token;const r=await fetch(API+path,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d}
async function register(){ $("authMsg").textContent="Creating account...";try{const d=await api("/api/auth/register",{method:"POST",body:JSON.stringify({username:$("regUser").value.trim(),email:$("regEmail").value.trim(),password:$("regPass").value})});token=d.token;localStorage.setItem("ludo_token",token);showHome()}catch(e){$("authMsg").textContent=e.message}}
async function login(){try{const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify({email:$("email").value.trim(),password:$("password").value})});token=d.token;localStorage.setItem("ludo_token",token);showHome()}catch(e){$("authMsg").textContent=e.message}}
async function showHome(){try{await loadProfile();await loadRooms();await loadLeaderboard();$("auth").hidden=true;$("home").hidden=false;$("status").textContent="Online"}catch(e){logout();$("authMsg").textContent=e.message}}
async function loadProfile(){const d=await api("/api/me"),u=d.user;$("profile").innerHTML=`<b>${u.username}</b><br>🪙 ${u.coins} virtual coins<br>🏆 Wins: ${u.wins} · Losses: ${u.losses}`}
async function loadLeaderboard(){const d=await api("/api/leaderboard");$("leaderboard").innerHTML=d.leaderboard.slice(0,10).map((u,i)=>`${i+1}. <b>${u.username}</b> — ${u.wins} wins · ${u.coins} coins`).join("<br>")||"No players yet."}
async function loadRooms(){const d=await api("/api/rooms");$("rooms").innerHTML=d.rooms.map(r=>`<div class="room"><b>${r.name}</b><br>${r.playerCount}/${r.maxPlayers} players · ${r.status}<br><button onclick="joinRoom(${r.id})">Join</button></div>`).join("")||"No rooms. Create one."}
async function createRoom(){try{const d=await api("/api/rooms",{method:"POST",body:JSON.stringify({name:"Ludo Room",maxPlayers:4})});currentRoom=d.room;renderGame()}catch(e){alert(e.message)}}
async function joinRoom(id){try{const d=await api("/api/rooms/"+id+"/join",{method:"POST"});currentRoom=d.room;renderGame()}catch(e){alert(e.message)}}
let pos=[0,0,0,0],started=false;
function renderGame(){if(!currentRoom)return;$("game").innerHTML=`<b>${currentRoom.name}</b><p>${currentRoom.players.length}/${currentRoom.maxPlayers} players</p><div class="board" id="board"></div><div class="dicebox"><div id="dice" class="dice">🎲</div><button onclick="startGame(${currentRoom.id})">Start</button><button onclick="roll(${currentRoom.id})">Roll Dice</button><div id="turn">Press Start</div></div><div class="hint">Local playable board demo. Server multiplayer token-sync can be added next.</div>`;drawBoard()}
function drawBoard(){const b=$("board");if(!b)return;b.innerHTML="";for(let r=0;r<15;r++)for(let c=0;c<15;c++){let x=document.createElement("div");x.className="cell";if(r<6&&c<6)x.classList.add("base-red");else if(r<6&&c>8)x.classList.add("base-green");else if(r>8&&c<6)x.classList.add("base-blue");else if(r>8&&c>8)x.classList.add("base-yellow");else if(r>=6&&r<=8&&c>=6&&c<=8)x.classList.add("center");b.appendChild(x)}["red","green","blue","yellow"].forEach((col,i)=>{let cells=b.children;let n=Math.min(224,pos[i]);let t=document.createElement("div");t.className="token "+col;cells[n].appendChild(t)})}
async function startGame(id){try{const d=await api("/api/rooms/"+id+"/start",{method:"POST"});currentRoom=d.room;started=true;pos=[0,0,0,0];renderGame()}catch(e){alert(e.message)}}
async function roll(id){if(!started){alert("Pehle Start dabaiye.");return}try{const d=await api("/api/rooms/"+id+"/dice",{method:"POST"});$("dice").textContent="🎲 "+d.dice;pos[0]=Math.min(224,pos[0]+d.dice);drawBoard();$("turn").textContent="You rolled "+d.dice+" — token moved";await loadProfile()}catch(e){alert(e.message)}}
function logout(){token=null;localStorage.removeItem("ludo_token");$("home").hidden=true;$("auth").hidden=false;$("status").textContent="Offline"}if(token)showHome();else $("auth").hidden=false;
